# Generated by Django 4.2.1 on 2023-06-01 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('TrinerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(max_length=50)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('NotificationID', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.user')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('LessonID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('duration', models.IntegerField()),
                ('order', models.IntegerField()),
                ('resources', models.URLField()),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('EnrollmentID', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('completion_status', models.BooleanField(default=False)),
                ('grade', models.CharField(max_length=10)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.user')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionForum',
            fields=[
                ('FormID', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.user')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Trinerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.trainer'),
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('ContactID', models.AutoField(primary_key=True, serialize=False)),
                ('RecipientID', models.IntegerField()),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.user')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('AssignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
            ],
        ),
    ]
