# Generated by Django 4.2.1 on 2023-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_trainer_description_trainerinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trainerinfo',
            name='Trainerinfo',
        ),
        migrations.AddField(
            model_name='trainerinfo',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
