# Generated by Django 4.2.1 on 2023-06-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_remove_trainer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerinfo',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='trainer/images'),
        ),
    ]
