# Generated by Django 4.2.1 on 2023-06-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_course_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='capacity',
            new_name='entrollment',
        ),
    ]
