# Generated by Django 4.2.1 on 2023-06-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_rename_capacity_course_entrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='entrollment',
        ),
        migrations.AddField(
            model_name='course',
            name='Enrollment',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
