# Generated by Django 4.2.1 on 2023-06-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_remove_course_entrollment_course_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='resources',
            field=models.FileField(default='', null=True, upload_to='lesson_resources/files'),
        ),
    ]
