# Generated by Django 4.2.1 on 2023-06-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_alter_lesson_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerinfo',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='trainer/images'),
        ),
    ]
