# Generated by Django 4.2.1 on 2023-06-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_remove_contactus_recipientid_contactus_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Enrollment',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
