# Generated by Django 4.2.1 on 2023-06-13 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_alter_course_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionforum',
            name='CourseID',
        ),
        migrations.RemoveField(
            model_name='discussionforum',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='CourseID',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='CourseID',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='UserID',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='DiscussionForum',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
